[book]
title = "rust計算物理学チュートリアル"
authors = ["sakuraba07"]
language = "ja"
src = "src"

[preprocessor.mermaid]

[preprocessor.typst-math]
fonts = ["Fira Math"]
preamble = """
#set page(width: auto, height: auto, margin: 0.2em, fill: none)
#set text(size: 15pt)
"""

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]

[output]
[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/sakuraba07/rust-computational-physics-tutorial"
edit-url-template = "https://github.com/sakuraba07/rust-computational-physics-tutorial/edit/main/{path}"
additional-css = ["theme/css/pagefind.css", "theme/css/last-changed.css", "theme/css/typst.css", "theme/css/japanese.css"]
additional-js = ["theme/budoux-loader.js"]

[output.html.search]
enable = false
