[book]
title = "rust計算物理学チュートリアル"
authors = ["sakuraba07"]
language = "ja"
src = "src"

[preprocessor.mermaid]

# [preprocessor.typst-math]

[output]
[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/sakuraba07/rust-computational-physics-tutorial"
edit-url-template = "https://github.com/sakuraba07/rust-computational-physics-tutorial/edit/main/{path}"
additional-css = ["theme/css/pagefind.css"]

[output.html.search]
enable = false
